### ISSUE TITLE
Invalid Calcs and Missing column references in Tabmon data source

### ISSUE THREAD

**Issue by srwoehrle** [tableau/TabMon#65] opened 2016-05-13 13:36 UTC
Hello,

I have an issue similar to this one ( https://github.com/tableau/TabMon/issues/62) .   However I am using Tableau Server Version: 9.1.0 (9100.15.0903.2142) 64-bit and the counters.config file has the webclientappservice names (not the old names).     Do you have any suggestions on how to restore the references?

I followed the Tabmon user guide for the setup and the JMX ports should be enabled.   I get other data in the tabmon data source which seems to confirm this too.

Local Tabmon repo invalid calcs or missing columns
%CPU gradient - invalid 
%RAM gradient - invalid

Not exist
%_disk_read_time
%_disk_write_time
%_free_space
Bytes_received/sec
Bytes_sent/sec
Current_disk_queue_length
Disk_read_bytes/sec
Disk_write_bytes/sec
Requests_failed
Requests_processed
%_processor_time
%_committed_bytes
average_batch_failure
average_batch_size
Average_query_latency
average_request_latency
heap_memory_usage\committed
heap_memory_usage\used
non_heap_memory_usage\committed
non_heap_memory_usage\used
Process
Request_processed
Thread_count
Total_compilation_time

Also I wanted to note that I am doing remote polling.    Tabmon polling database and tools are installed on my laptop which has access to the dev server.   At first I thought firewalls, but I am getting data coming into the tabmon database.   But I am open to suggestions!

Here is a screenshot of the config file.
![capture](https://cloud.githubusercontent.com/assets/19347175/15249744/3981f870-18ef-11e6-9c09-1b57b2434c43.JPG)

Thanks for your help in advance!

**Comment by srwoehrle** [comment] 2016-05-13 13:45
Added an attachment

**Comment by timlatona** [comment] 2016-06-10 16:10
I'm also having this issue. Server is 9.1.3, jmx counters are enabled, but many of the measures don't appear in the db.

**Comment by jmangue** [comment] 2016-06-15 18:35
Hi srwoehle,

Yikes, that is a lot of missing columns...!

Your config looks correct.  I'm guessing the issue is probably permissions related.. is the TabMon service on your laptop running as a user that has permissions to poll Perfmon on the target machine?  The service account that TabMon runs as must either be an admin account or be a member of the "Performance Monitor Users" and "Performance Log Users" domain group on every server you wish to remotely monitor.  Changing the RunAs user is covered in "Remote Polling Setup" in the user guide.

Another thing to check is that the following two Windows services are running on the remote machine you wish to gather Perfmon samples from: "Remote Registry" & "Performance Logs & Alerts".  These are typically running in Windows but occasionally an administrator may have disabled them.

**Comment by srwoehrle** [comment] 2016-06-15 18:46
Justin,


Yes, that was the problem that I had.   Our SAs did not want to give me the network credentials that had the permissions you mentioned.   Instead they polled the counters locally into postgress on the Dev box, then gave me postgres credentials to that local postgres DB.


Thanks,
Sean






Sent from Windows Mail





From: Justin Mangue
Sent: ‎Wednesday‎, ‎June‎ ‎15‎, ‎2016 ‎2‎:‎35‎ ‎PM
To: tableau/TabMon
Cc: Sean Woehrle, Author





Hi srwoehle,

Yikes, that is a lot of missing columns...!

Your config looks correct. I'm guessing the issue is probably permissions related.. is the TabMon service on your laptop running as a user that has permissions to poll Perfmon on the target machine? The service account that TabMon runs as must either be an admin account or be a member of the "Performance Monitor Users" and "Performance Log Users" domain group on every server you wish to remotely monitor. Changing the RunAs user is covered in "Remote Polling Setup" in the user guide.

Another thing to check is that the following two Windows services are running on the remote machine you wish to gather Perfmon samples from: "Remote Registry" & "Performance Logs & Alerts". These are typically running in Windows but occasionally an administrator may have disabled them.

**Comment by jmangue** [comment] 2016-07-26 22:42
Closing out, let me know if you need any more help.

**Closed by jmangue** 2016-07-26 22:42 UTC
Labels: help wanted
