### ISSUE TITLE
TabMon won't start up after upgrade to 10.3.5

### ISSUE THREAD

**Issue by karlmaire** [tableau/TabMon#162] opened 2017-12-05 23:21 UTC
Hi,

We recently upgraded our Tableau Server to v10.3.5, and now TabMon (v1.1) refuses to start up. Below is a snippet from the log where it gets stuck:

2017-12-06 11:34:33,348 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (9402), stopping scan.
2017-12-06 11:34:33,348 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 10000-10299 on tableauserver..
2017-12-06 11:34:33,426 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at tableauserver:10000
2017-12-06 11:34:33,426 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for tableauserver:10000

I tested this in our test environment prior to the upgrade, and it all worked fine, but since I only have a single test server, TabMon and Tableau Server are on the same VM. In production, these are located on separate VM's, so I have asked for network to check the firewall.

Apart from network, any other ideas?

**Comment by danjrahm** [comment] 2017-12-05 23:53
Can you attach a full set of logs? Preferably after they have been deleted and the issue is reproduced.

**Comment by karlmaire** [comment] 2017-12-06 00:05
Hi Dan,

Here is the log file 
[TabMon.log.txt](https://github.com/tableau/TabMon/files/1533399/TabMon.log.txt) The server name has been obfuscated of course.

For testing this issue, I have been using the standard Counters.config file with no changes.

**Comment by danjrahm** [comment] 2017-12-06 00:50
By standard Counters.config do you mean the counters that are used when TabMon is deployed? If so can you retry with the Counters.config located here? 
TABMONROOT\TabMon\Resources\Configurations\10.2+

**Comment by karlmaire** [comment] 2017-12-06 01:35
I am using the config from 9.3 - 10.0. I don't have a folder with configurations from 10.2+. I can also confirm that this same config works fine in my test environment with Tableau Server v10.3.5.

**Comment by karlmaire** [comment] 2017-12-06 03:02
I have also tested with the file from TabMon 1.2 for 10.2+. No change. It does however, still work in my test environment using the same config for 10.2+.

**Comment by danjrahm** [comment] 2017-12-07 01:05
My assumption is that TabMon is hanging. How long did you wait before killing the startup attempt?

As our next troubleshooting steps can you do the following?

1. Check netstat to see if anything is running between ports 10000 and 10299.
2. Edit the 'dataserver' section of the Counters.config to only scan port 10000. The section should look like this:

**Comment by karlmaire** [comment] 2017-12-08 01:52
I have just logged on to the server and started TabMon up to test, but it all now appears to be working, with no issues.

My assumption here is the network team eventually looked into the firewall and made some changes, but I haven't heard back.

I also thought it might be hanging, the service took forever to start and then seemed to get stuck and it had to be manually killed. If it was the network as I suspect (due to it working in test), this could be a bug?

Thanks for your assistance with this one.

**Comment by danjrahm** [comment] 2017-12-12 19:20
I'm glad this is working for you. I've created a new issue to implement a retry/timeout during the connection (Issue #163).

I am going to close this now.

**Closed by danjrahm** 2017-12-12 19:20 UTC
