### ISSUE TITLE
Many measures dont exist

### ISSUE THREAD

**Issue by jgebhardt13** [tableau/TabMon#29] opened 2015-12-09 09:33 UTC
All of the Memory, CPU, Disk, and Network dashboards load for me, but Cache Hits, Users, Requests and Latency dont load because the measures used in those sheets/dashboards dont exist in my Postgres repo.  See the attached image - a ton of my measures dont exist.  Any ideas?  (bear in mind this is my local server which only gets used lightly by myself)
![tabmon measures](https://cloud.githubusercontent.com/assets/15941156/11681589/c449c720-9e57-11e5-9740-7f5d6896734e.png)

**Comment by mitchko** [comment] 2015-12-09 15:04
I am having the same problem. Looking at the Production TabMon Postgres database (where I am having the problem) and comparing it to my Development (TabMon Postgres database)I am missing approximately 25 columns from the Production TabMon Postgrex database.

**Comment by mitchko** [comment] 2015-12-09 15:39
After further investigation I found the following columns missing.  I've included them and the statement to create.  I hope within the next few hours the information will begin to populate the columns.

average_request_latency 		ALTER TABLE countersamples ADD COLUMN average_request_latency double precision;
requests_failed 		ALTER TABLE countersamples ADD COLUMN requests_failed double precision;
requests_processed 		ALTER TABLE countersamples ADD COLUMN requests_processed double precision;
average_batch_failure 	ALTER TABLE countersamples ADD COLUMN average_batch_failure double precision;	
average_batch_size 		ALTER TABLE countersamples ADD COLUMN average_batch_size double precision;
average_query_latency 		ALTER TABLE countersamples ADD COLUMN average_query_latency double precision;
request_processed 		ALTER TABLE countersamples ADD COLUMN request_processed double precision;
total_compilation_time 	ALTER TABLE countersamples ADD COLUMN total_compilation_time double precision;
heap_memory_usage\committed 	ALTER TABLE countersamples ADD COLUMN "heap_memory_usage\committed" double precision;	
heap_memory_usage\used 	ALTER TABLE countersamples ADD COLUMN "heap_memory_usage\used" double precision;	
non_heap_memory_usage\committed ALTER TABLE countersamples ADD COLUMN "non_heap_memory_usage\committed" double precision;		
non_heap_memory_usage\used 	ALTER TABLE countersamples ADD COLUMN "non_heap_memory_usage\used" double precision;	
external_abstract_query_cache_hits 	ALTER TABLE countersamples ADD COLUMN external_abstract_query_cache_hits double precision;	
external_abstract_query_cache_misses 	ALTER TABLE countersamples ADD COLUMN external_abstract_query_cache_misses double precision;	
external_query_cache_hits 	ALTER TABLE countersamples ADD COLUMN external_query_cache_hits double precision;	
external_query_cache_misses ALTER TABLE countersamples ADD COLUMN external_query_cache_misses double precision;		
in_process_abstract_query_cache_hits 	ALTER TABLE countersamples ADD COLUMN in_process_abstract_query_cache_hits double precision;	
in_process_abstract_query_cache_misses 	ALTER TABLE countersamples ADD COLUMN in_process_abstract_query_cache_misses double precision;	
in_process_query_cache_hits 	ALTER TABLE countersamples ADD COLUMN in_process_query_cache_hits double precision;	
in_process_query_cache_misses ALTER TABLE countersamples ADD COLUMN in_process_query_cache_misses double precision;		
visual_model_cache_hits 	ALTER TABLE countersamples ADD COLUMN visual_model_cache_hits double precision;	
visual_model_cache_misses 	ALTER TABLE countersamples ADD COLUMN visual_model_cache_misses double precision;	
visual_model_cache_partial_hits 	ALTER TABLE countersamples ADD COLUMN visual_model_cache_partial_hits double precision;	
image_cache_hits 	ALTER TABLE countersamples ADD COLUMN image_cache_hits double precision;	
image_cache_misses 	ALTER TABLE countersamples ADD COLUMN image_cache_misses double precision;	
active_sessions 	ALTER TABLE countersamples ADD COLUMN active_sessions double precision;	
requests_count ALTER TABLE countersamples ADD COLUMN requests_count double precision;

**Comment by mchentableau** [comment] 2015-12-09 16:58
For this particular problem, did you first enable jmx port monitoring on your Tableau server as stated in the installation doc?

**Comment by mitchko** [comment] 2015-12-09 17:01
I did.  However, upon checking the config file now it is not enabled.  This is the second time I’ve had this problem with parameter changes.  I will update the open case I have on this.

Should I uninstall Tabmon and re-install once after I get JMX enabled?

Thanks Michael!

**Comment by mchentableau** [comment] 2015-12-09 17:04
You don't need to reinstall TabMon, but you should restart it after the server is properly setup.

**Comment by jgebhardt13** [comment] 2015-12-09 17:21
Yes, JMX is enabled on mine 
![image](https://cloud.githubusercontent.com/assets/15941156/11692772/3a22ecba-9e99-11e5-9e5a-58be3330b100.png)

**Comment by jmangue** [comment] 2015-12-09 17:30
As Michael mentioned, it looks like none of the JMX data is being collected, which is why those columns are missing.  TabMon creates and manages it's own table schema -- you should not add any columns manually.

jgebhardt13 -- did you enable JMX using the tabadmin commands listed in the TabMon user guide?  I ask because typically that key shows up as "service.jmx_enabled" in the workgroup.yml file, not just "jmx_enabled".

**Comment by jgebhardt13** [comment] 2015-12-09 17:34
Aha!  I did use tabadmin, but I must have looked in the workgroup.yml file and found the 'jmx_enabled' setting in there and typed that into tabadmin instead of putting 'service.' in front.  I will run tabadmin again to flip that guy to true as well.  Thanks!

**Comment by jmangue** [comment] 2015-12-09 17:36
No problem!  tabadmin unfortunately doesn't do any validation on keys that you set, so these kinds of mistakes are easy to make :)  After doing "tabadmin set service.jmx_enabled true", you'll need to run "tabadmin configure" afterwards as well, and then restart Tableau Server... and finally restart TabMon.  Let us know how it goes!

**Comment by jgebhardt13** [comment] 2015-12-09 17:52
It works now :)

**Comment by jmangue** [comment] 2015-12-09 18:21
Awesome!

mitchko, let me know how it goes.

**Comment by mitchko** [comment] 2015-12-10 13:05
Fixed!!! I had to cycle the system last night to update some additional parameters and this time JMX STAYED enabled.

Thanks for your input and direction on solving this.

**Comment by jmangue** [comment] 2015-12-17 22:29
Closing this out since it sounds like the issue is fixed for both of you. :) Let me know if anything else comes up!

**Closed by jmangue** 2015-12-17 22:29 UTC

**Comment by ManoSahoo165** [comment] 2016-03-07 14:30
Hello Team,
we installed Tabmon on our environment (version 9.0). but while validating data we are getting blank for Network sheet and we have null values for measures present on dashboard.

Kindly Help me to fix the issue.

Thanks
Manoj

**Comment by danjrahm** [comment] 2016-03-07 21:16
@ManoSahoo165 
Moved this request for assistance to issue #49. I will respond there.
