### ISSUE TITLE
Not able to cofigure TABMON

### ISSUE THREAD

**Issue by malreddypraveenreddy** [tableau/TabMon#161] opened 2017-12-04 12:50 UTC
HI All
please help me in tabmon setup . I am facing issues in opening the workbook after installation. It is saying invalid password. Hope you guys are already setup environment for your projects. Please help me on this .

Below is my number . Please feel free to contact me or guide me
9666410002

**Comment by danjrahm** [comment] 2017-12-05 18:56
Hello,

Before we continue I have a couple of questions about the TabMon configuration and environment.

1. Is TabMon installed and running without errors?
2. Can you confirm that postgres is setup and running as expected? Can you log into it using PGAdminIII
3. Was the readonly user enabled for Tableau Server?

The two passwords that are requested when the workbook is opened are the TabMon Postgres password and the Tableau Server read only password. So, one of these will be the cause of the error.

-Dan

**Comment by danjrahm** [comment] 2018-02-14 00:59
Hello, 

I am going to close this since there has not been a response.
If you need any further assistance let me know.

-Dan

**Closed by danjrahm** 2018-02-14 00:59 UTC
