### ISSUE TITLE
Wanted TabMon Log clarification

### ISSUE THREAD

**Issue by rishabh1991** [tableau/TabMon#60] opened 2016-04-07 08:39 UTC
Hi 

Below is the TabMon log file showing many failures. Please clarify what necessary changes should I do to get it alinged?

Log file:

2016-04-07 04:33:30,040 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Network Interface\Bytes Received/sec\: Counter is not single instance, an instance name needs to be specified.
2016-04-07 04:33:30,040 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Network Interface\Bytes Sent/sec\: Counter is not single instance, an instance name needs to be specified.
2016-04-07 04:33:31,210 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#9: Instance 'tabprotosrv#9' does not exist in the specified Category.
2016-04-07 04:33:31,257 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#10: Instance 'tabprotosrv#10' does not exist in the specified Category.
2016-04-07 04:33:31,272 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#5: Instance 'tabprotosrv#5' does not exist in the specified Category.
2016-04-07 04:33:31,288 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#4: Instance 'tabprotosrv#4' does not exist in the specified Category.
2016-04-07 04:33:31,335 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#3: Instance 'tabprotosrv#3' does not exist in the specified Category.
2016-04-07 04:33:31,350 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#7: Instance 'tabprotosrv#7' does not exist in the specified Category.
2016-04-07 04:33:31,366 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#6: Instance 'tabprotosrv#6' does not exist in the specified Category.
2016-04-07 04:33:31,382 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#11: Instance 'tabprotosrv#11' does not exist in the specified Category.
2016-04-07 04:33:31,397 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\% Processor Time\tabprotosrv#8: Instance 'tabprotosrv#8' does not exist in the specified Category.
2016-04-07 04:33:32,864 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#9: Instance 'tabprotosrv#9' does not exist in the specified Category.
2016-04-07 04:33:32,910 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#10: Instance 'tabprotosrv#10' does not exist in the specified Category.
2016-04-07 04:33:32,926 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#5: Instance 'tabprotosrv#5' does not exist in the specified Category.
2016-04-07 04:33:32,942 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#4: Instance 'tabprotosrv#4' does not exist in the specified Category.
2016-04-07 04:33:33,004 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#3: Instance 'tabprotosrv#3' does not exist in the specified Category.
2016-04-07 04:33:33,020 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#7: Instance 'tabprotosrv#7' does not exist in the specified Category.
2016-04-07 04:33:33,035 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#6: Instance 'tabprotosrv#6' does not exist in the specified Category.
2016-04-07 04:33:33,051 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#11: Instance 'tabprotosrv#11' does not exist in the specified Category.
2016-04-07 04:33:33,066 [7] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\wtabqnas01\Perfmon\Process\Working Set\tabprotosrv#8: Instance 'tabprotosrv#8' does not exist in the specified Category.
2016-04-07 04:33:33,378 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.getview\AverageRequestLatency\vizportal: Unable to query MBean.
2016-04-07 04:33:33,378 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.getview\RequestsFailed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,378 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.getview\RequestsProcessed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,378 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.guestlogin\AverageRequestLatency\vizportal: Unable to query MBean.
2016-04-07 04:33:33,378 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.guestlogin\RequestsFailed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,378 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.guestlogin\RequestsProcessed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextracttasks\AverageBatchFailure\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextracttasks\AverageBatchSize\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextracttasks\AverageRequestLatency\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextracttasks\RequestsFailed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextracttasks\RequestsProcessed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesonworkbooks\AverageBatchFailure\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesonworkbooks\AverageBatchSize\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesonworkbooks\AverageRequestLatency\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesonworkbooks\RequestsFailed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesonworkbooks\RequestsProcessed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesondatasources\AverageBatchFailure\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesondatasources\AverageBatchSize\vizportal: Unable to query MBean.
2016-04-07 04:33:33,410 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesondatasources\AverageRequestLatency\vizportal: Unable to query MBean.
2016-04-07 04:33:33,425 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesondatasources\RequestsFailed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,425 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runextractrefreshesondatasources\RequestsProcessed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,425 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runschedules\AverageBatchFailure\vizportal: Unable to query MBean.
2016-04-07 04:33:33,425 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runschedules\AverageBatchSize\vizportal: Unable to query MBean.
2016-04-07 04:33:33,425 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runschedules\AverageRequestLatency\vizportal: Unable to query MBean.
2016-04-07 04:33:33,425 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runschedules\RequestsFailed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,425 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.runschedules\RequestsProcessed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,441 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.login\AverageRequestLatency\vizportal: Unable to query MBean.
2016-04-07 04:33:33,441 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.login\RequestsFailed\vizportal: Unable to query MBean.
2016-04-07 04:33:33,441 [7] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\wtabqnas01\vizportal\tableau.health.jmx:name=webclientappservice.login\RequestsProcessed\vizportal: Unable to query MBean

**Comment by GirlMeetsData** [comment] 2016-04-07 15:49
Look at FAQ #4 and #5: https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf

Also, did you run the tabadmin command to enable JMX?

**Comment by danjrahm** [comment] 2016-04-07 20:37
Hello,

It looks like you are hitting 2 issues here. The first, as mentioned above, is that it looks like JMX is not enabled on Tableau Server.

The multi instance issue looks to be caused by this defect #22.

Enabling the JMX counters (using the user guide) will remove the bulk of the errors. The rest of the errors will be taken care of using a code fix.

**Comment by jmangue** [comment] 2016-06-15 18:18
Closing as answered.

**Closed by jmangue** 2016-06-15 18:18 UTC
