### ISSUE TITLE
Unable to install TabMon in Windows 2012 R2 standard OS

### ISSUE THREAD

**Issue by gunacom** [tableau/TabMon#116] opened 2017-04-17 14:49 UTC
Hi, 

I am trying to install Tabmon v1.1 in to Windows 2012 R2 standard OS, but I can't. Because I could not install any of the verisons of Windows Management Framework like 3.0 or 4.0 and even 5.0. 

Please guide me, the prequisite to install TabMon in Windows 2012 R2 standard OS.

**Comment by danjrahm** [comment] 2017-04-17 17:06
Looking into this now. I'll try standing TabMon up in Windows 2012 R2. 
This may be a permissions issue.

**Comment by danjrahm** [comment] 2017-04-17 17:53
I was able to successfully install Tabmon V1.1 on Windows 2012 R2. 

What error is received when attempting to install? Is it the 'Setup Failed - Windows Management Framework 3.0 is required for installation' error?

Also, when attempting to install WMF is there an exception? 

Thanks,
Dan

**Comment by gunacom** [comment] 2017-04-18 02:50
Hi, 

Thanks for your prompt response. 

Installation got failed at the time of installting Postgre DB, if I exclude that one, then the installation got successful. Hence, 

Is it really needed to install Postgre DB? because I would like to utilize Postgre DB which is present in Tableau instead of installting the new one.  

Also, if TabMon permits to use Postgre DB of tableau, then how do i configure that one.. Please suggest and help me out

**Comment by danjrahm** [comment] 2017-04-18 02:59
Hello,

Using Tableau Server's Postgres is not supported. Please do not attempt to store TabMon data in the Tableau Postgres instance.

Based on the new information it does not sound like the issue is due to WMF. Instead it sounds like the configuration script is not successfully running. To workaround this, please refer to the 'Manually Installing & Configuring Postgres' of our [user guide](https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf).

If there are any issues with the guide please let me know.

-Dan

**Comment by gunacom** [comment] 2017-04-25 10:16
Hi Dan, 

We have successfully configured TabMon in  Tableau server. 

We have taken the CounterSample Workbook from Resources folder and published in to Tableau Server by using pre existing Server Auditing Tableau Postgre tables. But still we have some clarifications on , 

1.  How do we find CounterSample table in the TabMon Postgre Database?
2. How do we alter the existing tabs/views, ie.) Concurrent Users , Active session etc?
3. How do we ensure, whether the displaying data showing the correct values or not?
4. Is there any tutorial to undestand, the method to publish TabMon Workbooks in to Tableau Servers?

**Comment by danjrahm** [comment] 2017-04-25 17:16
Hello,

I'm happy to hear the things are up and running.

1. The countersamples table can be found using any console that can connect to postgres. To do so, use the postgres account used by TabMon and create a connection to the postgres database. After that the data should be stored using the following information.
Database: TabMon
Schema: Public
Tables: countersamples

2. Any existing tabs can be altered using Tableau Desktop. We don't really have a guide on best practices for building the views though. This tutorial may help with some best practices for using Tableau Desktop: https://onlinehelp.tableau.com/current/pro/desktop/en-us/getstarted_tutorial.html

3. Ensuring that the data is accurate can be done using various methods. It all really depends on the counter that is being looked at. A good portion of counters can be validated using the Tableau Server admin dashboards, some of the values will need to be inferred though. As for the windows performance counters, these can be validated using either PerfMon or the Resource Monitor.

4. Tableau Support has a pretty good guide on publishing workbooks. It can be found here:
https://onlinehelp.tableau.com/current/pro/desktop/en-us/publish_workbooks_howto.html

Let me know if there are any other questions.

-Dan

**Comment by gunacom** [comment] 2017-04-26 10:32
Hi Dan, 

Thank you so much for your prompt response. 

Is there any tutorial to understand effectiveness of each and every tab present in the counter samples?
Also is there any other workbook/tables available to monitor workbook related statistics, other than Counter Samples?

Please assist. 

/Guna

**Comment by danjrahm** [comment] 2017-04-26 20:54
Hello, 

There really isn't a tutorial on the workbook itself. The workbook is supposed to be an example of how TabMon can be used and how the information that can be displayed. For the tabs themselves, there are some descriptions that should help explain the worksheets/dashboards.

As for the JMX counters that are exposed, we do not currently have a guide on the counters. There is however a fairly in depth article on the performance counter that are collected:
https://technet.microsoft.com/en-us/library/cc976785.aspx

It may be worth submitting a feature request to Tableau Support or starting a topic on the Tableau forums to talk about the counters.




Countersamples is the only table we create. It is a mixture of the JMX and perfmon counters that are enabled in the config. 

There are some tables exposed by the Tableau Server readonly user that can be mixed with the data. Here is a guide on that:
https://onlinehelp.tableau.com/current/server/en-us/adminview_postgres.htm

Let me know if there's anything else I can help with.

-Dan

**Comment by jmangue** [comment] 2017-06-26 17:27
Closing this one out.

**Closed by jmangue** 2017-06-26 17:27 UTC
