### ISSUE TITLE
Unable to collect metrics for worker nodes & enable remote logon for tabmon

### ISSUE THREAD

**Issue by Shobananpa** [tableau/TabMon#78] opened 2016-07-22 14:32 UTC
Hi Team,

Here are the issues we are facing in executing the tabmon, need assistance to get this running soon.
1. we installed tabmon on our primary gateway server and when I go to tabmon service properties & try to enable the log on as "This account" I get "Access Denied" error message.
2. Tabmon goes to running state only when I give the Log on as "Local System Account".
3. On the sample workbook, we are not able to capture the visuals for tableau server processes running on worker nodes.
4. Though we enabled JMX port, we are seeing this on the tabmon error log.
2016-07-22 10:04:42,862 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 8900-8999 on Primary gateway..
2016-07-22 10:04:44,674 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (8900), stopping scan.
2016-07-22 10:04:44,674 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 9400-9499 on Primary gateway..
2016-07-22 10:04:45,690 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (9400), stopping scan.
2016-07-22 10:04:45,690 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 10000-10299 on Primary gateway..
2016-07-22 10:04:46,705 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (10000), stopping scan.
2016-07-22 10:04:46,705 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 0 MBean counters on Primary gateway.
2016-07-22 10:04:46,705 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 8900-8999 on Backup gateway..
2016-07-22 10:04:47,737 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (8900), stopping scan.
2016-07-22 10:04:47,737 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 9400-9499 on Backup gateway..
2016-07-22 10:04:48,737 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (9400), stopping scan.
2016-07-22 10:04:48,737 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 10000-10299 on Backup gateway..
2016-07-22 10:04:49,737 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (10000), stopping scan.
2016-07-22 10:04:49,737 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 0 MBean counters on Backup gateway.
2016-07-22 10:04:49,737 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 8900-8999 on Worker1..
2016-07-22 10:04:49,971 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker1:8900
2016-07-22 10:04:49,971 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker1:8900
2016-07-22 10:04:49,987 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker1:8901
2016-07-22 10:04:49,987 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker1:8901
2016-07-22 10:04:51,002 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (8902), stopping scan.
2016-07-22 10:04:51,002 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 9400-9499 on Worker1..
2016-07-22 10:04:51,018 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker1:9400
2016-07-22 10:04:51,018 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker1:9400
2016-07-22 10:04:51,049 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker1:9401
2016-07-22 10:04:51,049 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker1:9401
2016-07-22 10:04:52,080 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (9402), stopping scan.
2016-07-22 10:04:52,080 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 10000-10299 on Worker1..
2016-07-22 10:04:52,080 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker1:10000
2016-07-22 10:04:52,080 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker1:10000
2016-07-22 10:04:52,096 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker1:10001
2016-07-22 10:04:52,096 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker1:10001
2016-07-22 10:04:53,112 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (10002), stopping scan.
2016-07-22 10:04:53,112 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 116 MBean counters on Worker1.
2016-07-22 10:04:53,112 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 8900-8999 on Worker2..
2016-07-22 10:04:53,112 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker2:8900
2016-07-22 10:04:53,112 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker2:8900
2016-07-22 10:04:53,127 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker2:8901
2016-07-22 10:04:53,127 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker2:8901
2016-07-22 10:04:54,143 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (8902), stopping scan.
2016-07-22 10:04:54,143 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 9400-9499 on Worker2..
2016-07-22 10:04:54,143 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker2:9400
2016-07-22 10:04:54,143 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker2:9400
2016-07-22 10:04:54,159 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker2:9401
2016-07-22 10:04:54,159 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker2:9401
2016-07-22 10:04:55,190 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (9402), stopping scan.
2016-07-22 10:04:55,190 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 10000-10299 on Worker2..
2016-07-22 10:04:55,190 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker2:10000
2016-07-22 10:04:55,190 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker2:10000
2016-07-22 10:04:55,205 [5] DEBUG TabMon.Counters.MBean.JmxConnectorProxy - Opened connection to JMX server at Worker2:10001
2016-07-22 10:04:55,205 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Created JMX client for Worker2:10001
2016-07-22 10:04:56,237 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (10002), stopping scan.
2016-07-22 10:04:56,237 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 116 MBean counters on Worker2.
5. Even though we provided the workernodes & backup gateway names on the tabmon config file,we see the below error message.
2016-07-22 10:04:41,721 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2016-07-22 10:04:41,752 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2016-07-22 10:04:41,752 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2016-07-22 10:04:41,909 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'localhost' to 'Primary gateway'.
2016-07-22 10:04:41,909 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'Backup gateway' to 'Backup gateway'.
2016-07-22 10:04:41,909 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'Worker1' to 'Worker1'.
2016-07-22 10:04:41,909 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'Worker2' to 'Worker2'.
2016-07-22 10:04:41,924 [5] INFO TabMon.Config.TabMonConfigReader - Successfully loaded TabMon config options! [Hosts='Primary\Primary gateway,Primary\Backup gateway,Primary\Worker1,Primary\Worker2', Writer='Database Writer (Postgres Driver)', PollInterval='30', TableName='countersamples']
2016-07-22 10:04:41,924 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2016-07-22 10:04:41,924 [5] INFO TabMon.TabMonAgent - Loading performance counters from D:\TabMon\Config\Counters.config..
2016-07-22 10:04:41,924 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Successfully validated 'Config\Counters.config' against 'Resources\CountersConfig.xsd'.
2016-07-22 10:04:41,924 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading Perfmon counters..
2016-07-22 10:04:42,127 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 62 Perfmon counters on Primary gateway.
2016-07-22 10:04:42,284 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,284 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Free Space' in category 'LogicalDisk' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,284 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,284 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Committed Bytes In Use' in category 'Memory' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,299 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,299 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Received/sec' in category 'Network Interface' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,299 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,299 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Sent/sec' in category 'Network Interface' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,299 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,299 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Read Time' in category 'PhysicalDisk' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,315 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,315 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Write Time' in category 'PhysicalDisk' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,315 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,315 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Current Disk Queue Length' in category 'PhysicalDisk' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,315 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,315 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Write Bytes/sec' in category 'PhysicalDisk' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,315 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,315 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Read Bytes/sec' in category 'PhysicalDisk' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,330 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,330 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Process' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,330 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,330 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Thread Count' in category 'Process' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,330 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,330 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Working Set' in category 'Process' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,346 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,346 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Processor' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,346 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Backup gateway': Access is denied
2016-07-22 10:04:42,346 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Processes' in category 'System' on host 'Backup gateway' does not exist.
2016-07-22 10:04:42,346 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 0 Perfmon counters on Backup gateway.
2016-07-22 10:04:42,534 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,534 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Free Space' in category 'LogicalDisk' on host 'Worker1' does not exist.
2016-07-22 10:04:42,549 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,549 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Committed Bytes In Use' in category 'Memory' on host 'Worker1' does not exist.
2016-07-22 10:04:42,549 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,549 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Received/sec' in category 'Network Interface' on host 'Worker1' does not exist.
2016-07-22 10:04:42,549 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,549 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Sent/sec' in category 'Network Interface' on host 'Worker1' does not exist.
2016-07-22 10:04:42,565 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,565 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Read Time' in category 'PhysicalDisk' on host 'Worker1' does not exist.
2016-07-22 10:04:42,565 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,565 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Write Time' in category 'PhysicalDisk' on host 'Worker1' does not exist.
2016-07-22 10:04:42,580 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,580 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Current Disk Queue Length' in category 'PhysicalDisk' on host 'Worker1' does not exist.
2016-07-22 10:04:42,580 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,580 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Write Bytes/sec' in category 'PhysicalDisk' on host 'Worker1' does not exist.
2016-07-22 10:04:42,580 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,580 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Read Bytes/sec' in category 'PhysicalDisk' on host 'Worker1' does not exist.
2016-07-22 10:04:42,596 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,596 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Process' on host 'Worker1' does not exist.
2016-07-22 10:04:42,596 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,596 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Thread Count' in category 'Process' on host 'Worker1' does not exist.
2016-07-22 10:04:42,612 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,612 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Working Set' in category 'Process' on host 'Worker1' does not exist.
2016-07-22 10:04:42,612 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,612 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Processor' on host 'Worker1' does not exist.
2016-07-22 10:04:42,612 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker1': Access is denied
2016-07-22 10:04:42,612 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Processes' in category 'System' on host 'Worker1' does not exist.
2016-07-22 10:04:42,612 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 0 Perfmon counters on Worker1.
2016-07-22 10:04:42,768 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,768 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Free Space' in category 'LogicalDisk' on host 'Worker2' does not exist.
2016-07-22 10:04:42,768 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,768 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Committed Bytes In Use' in category 'Memory' on host 'Worker2' does not exist.
2016-07-22 10:04:42,784 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,784 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Received/sec' in category 'Network Interface' on host 'Worker2' does not exist.
2016-07-22 10:04:42,784 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,784 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Sent/sec' in category 'Network Interface' on host 'Worker2' does not exist.
2016-07-22 10:04:42,784 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,784 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Read Time' in category 'PhysicalDisk' on host 'Worker2' does not exist.
2016-07-22 10:04:42,799 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,799 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Write Time' in category 'PhysicalDisk' on host 'Worker2' does not exist.
2016-07-22 10:04:42,799 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,799 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Current Disk Queue Length' in category 'PhysicalDisk' on host 'Worker2' does not exist.
2016-07-22 10:04:42,815 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,815 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Write Bytes/sec' in category 'PhysicalDisk' on host 'Worker2' does not exist.
2016-07-22 10:04:42,815 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,815 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Read Bytes/sec' in category 'PhysicalDisk' on host 'Worker2' does not exist.
2016-07-22 10:04:42,830 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,830 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Process' on host 'Worker2' does not exist.
2016-07-22 10:04:42,830 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,830 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Thread Count' in category 'Process' on host 'Worker2' does not exist.
2016-07-22 10:04:42,846 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,846 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Working Set' in category 'Process' on host 'Worker2' does not exist.
2016-07-22 10:04:42,846 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,846 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Processor' on host 'Worker2' does not exist.
2016-07-22 10:04:42,862 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'Worker2': Access is denied
2016-07-22 10:04:42,862 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Processes' in category 'System' on host 'Worker2' does not exist.
Not sure, where we are doing wrong, need assistance.
[Tabmon logfile.txt](https://github.com/tableau/TabMon/files/378402/Tabmon.logfile.txt)
[Tabmon Config.txt](https://github.com/tableau/TabMon/files/378403/Tabmon.Config.txt)
[DB creation log.txt](https://github.com/tableau/TabMon/files/378404/DB.creation.log.txt)

**Comment by russch** [comment] 2016-07-23 11:01
Most of these don't have a lot to do with TabMon - a little bit of Googling will probably answer them for you, but here's a push in the right direction: 

1. You didn't mention if you get this error when you start the service, or when you attempt to change the account it runs under. If you can't start the service under a specific account, it probably just means the account in question doesn't have the correct permissions on the OS to access the resources you need. Try using an account with more permissions (start with an Admin account and see if that makes a difference)

2. Localsystem is a very permissive account, so this makes sense. 

3: LOCALSYSTEM has no permissions on any of your remote machines - it is a local account. Therefore one wouldn't expect to be able to collect perfmon counters on the other machines. You need to run the service under an account that has access to ALL machines. 

4. This question has been asked several times on this. Scan the "issues" list and you'll see it addressed.

**Comment by Shobananpa** [comment] 2016-07-25 13:00
Hi Russel,

Thanks for your response, I'm using the same credentials to run tableau server and on our non production environment(NPE), it works fine, on NPE I'm able to get views for the workers and able to run as "this account" on remote machines. I ll once again check with our IT team.
Thanks,
Shoba

**Comment by danjrahm** [comment] 2016-07-25 17:09
Hello, 

You may also want to verify that the TabMon service user is (at minimum) a member of the "Performance Monitor Users" and "Performance Log Users" domain group on every server you wish to remotely monitor.

This should help resolve the 'Access is denied' issue.

**Comment by Shobananpa** [comment] 2016-07-25 17:36
Hi,

The run as account is part of local system administrator and is added to
performance monitor users and performance log users.
Regards,
Shoba

**Comment by Shobananpa** [comment] 2016-07-26 14:58
Daniel/Russell,
Do we need to open the port 5432 on all the servers?

**Comment by jmangue** [comment] 2016-07-26 17:20
Port 5432 only needs to be opened on the machine where you are running TabMon, as it is the port that Postgres will run on by default.

**Comment by Shobananpa** [comment] 2016-07-26 20:32
Hi All,

I'm able to run the tabmon service using the log on as "This account".
But when I include the worker node 2 ip address in tabmon config file and try to start the service it gives me access denied error.
Able to do remote polling on backup gateway & worker node 1.

Thanks,
Shoba

**Comment by jmangue** [comment] 2016-07-26 21:00
It sounds like the account you are using does not have proper permissions on worker node 2.  Try checking to see what is different between how the account is configured on worker 1 vs worker 2.

**Comment by Shobananpa** [comment] 2016-07-26 21:12
Sure I ll work with Windows team.

**Comment by jmangue** [comment] 2016-08-05 22:19
@Shobananpa did you manage to get the permissions issue resolved?

**Comment by jmangue** [comment] 2016-08-06 00:00
You can try sending me the TabMon logs showing a failed TabMon service startup due to "Access Denied" and I'll take a look.  I don't know how much I'll be able to find though, as it sounds like something in your environment setup is blocking communication to worker 2.  Tableau Server logfiles won't be any help here.

**Comment by Shobananpa** [comment] 2016-08-06 02:42
Thanks Justin,
Attached the tabmon error log.
I see so many error message, related to tabprotosrv, tdeserver64, postgres.
2016-08-05 22:22:45,298 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Scanning JMX ports 8900-8999 on gateway2..
2016-08-05 22:22:47,126 [5] DEBUG TabMon.Counters.MBean.MBeanClientFactory - Encountered closed JMX port (8900), stopping scan.
We already opened all the JMX ports not able to understand why we get these error message.
Is this anything related to access issue.

Shoba

[tabmon error log 08-05.txt](https://github.com/tableau/TabMon/files/404851/tabmon.error.log.08-05.txt)

**Comment by jmangue** [comment] 2016-08-10 00:25
Hi Shoba,

As best I can tell from your logs, TabMon is failing to start because one (or more) of the PerfMon Categories it is trying to query does not exist (or is inaccessible) on Worker 2.  TabMon assumes the following 7 categories exist on each target system:

- LogicalDisk
- Memory
- Network Interface
- PhysicalDisk
- Process
- Processor
- System

If you open PerfMon on Worker 2 and scroll through the list of the "Available Counter" at the top left, are any of the above missing from the list?

In any case I will probably open up a bug to fix this ASAP.

**Comment by Shobananpa** [comment] 2016-08-10 01:43
Thanks Justin,

I ll look at it and get back to you.

Shoba

**Comment by jmangue** [comment] 2016-08-25 18:23
Hey Shoba, the bug you were hitting where the non-existence of a performance counter category on worker 2 can cause the service to fail to start has been fixed in TabMon v1.1.

**Comment by Shobananpa** [comment] 2016-08-26 01:59
Wow, that's a great news, thank you.

Shoba

**Comment by jmangue** [comment] 2016-09-26 17:39
Closing this out now that the root cause has been addressed in TabMon v1.1.

**Closed by jmangue** 2016-09-26 17:39 UTC
Labels: help wanted, question
