### ISSUE TITLE
Enhancement request: When using remote polling, TabMon should recover from remote machine restarts

### ISSUE THREAD

**Issue by jmangue** [tableau/TabMon#95] opened 2016-10-04 21:02 UTC
When using remote polling, communication with the remote nodes can be broken by system restarts.  This is a feature request to update TabMon to detect down nodes and recover when they come back online, without requiring a service restart.

**Comment by danjrahm** [comment] 2017-09-25 18:39
I've spent a couple of hours trying to reproduce this issue. So far it looks like the PerfMon counters recover properly after shutting down remote hosts. 

If this issue does occur again, we do have a potential fix. I am going to avoid making that change unless absolutely necessary. 

Closing this out.

**Closed by danjrahm** 2017-09-25 18:39 UTC
Labels: enhancement, suggestion
