### ISSUE TITLE
Unable to start the tabmon service

### ISSUE THREAD

**Issue by Tabuser** [tableau/TabMon#9] opened 2015-11-05 06:37 UTC
Hi,

I just installed the Tabmon successfully with the service account that has admin privileges. But when I try to start the Tabmon service from the services.msc, I am getting the below error. Can someone help me on this?
![image](https://cloud.githubusercontent.com/assets/15665972/10961530/b4361fd8-835d-11e5-84a4-80b64572ece0.png)

**Comment by danjrahm** [comment] 2015-11-05 17:37
Hello,

To look into this I will need the TabMon.log file. This can be found in the Logs folder of the TabMon directory. (Default directory: C:\Program Files (x86)\TabMon\Logs)

Once I have these I should be able to see why we are receiving the error.

**Comment by Tabuser** [comment] 2015-11-05 20:16
Please see the below notes from the logs.

2015-11-05 00:56:46,896 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2015-11-05 00:56:46,896 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2015-11-05 00:56:46,896 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)

**Comment by danjrahm** [comment] 2015-11-05 21:58
From that snippet it looks like this issue could be caused by a few things.
1. The TabMon config is incorrectly configured.
2. Postgres is not properly initialized.

For me to determine the exact cause, I will need the following.
1. The full TabMon log file. (You can drag and drop it into the comment box here)
2. The DBCreation log file. (This can be found in the temp directory)
3. TabMon config file. (This can be found in the Config folder of the Tabmon directory)

Let me know if there are any questions.

**Comment by Tabuser** [comment] 2015-11-05 22:04
here is the tabmon log file.

2015-11-05 15:56:24,334 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2015-11-05 15:56:24,381 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2015-11-05 15:56:24,381 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2015-11-05 15:56:24,647 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"
2015-11-05 15:56:24,647 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'localhost' to '<TableauServer>'.
2015-11-05 15:56:24,663 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\<TableauServer>', Writer='null', PollInterval='30', TableName='countersamples']
2015-11-05 15:56:24,663 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2015-11-05 15:56:24,663 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2015-11-05 15:56:24,663 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2015-11-05 15:57:20,554 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2015-11-05 15:57:20,601 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2015-11-05 15:57:20,601 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2015-11-05 15:57:20,851 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"
2015-11-05 15:57:20,867 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'localhost' to '<TableauServer>'.
2015-11-05 15:57:20,867 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\<TableauServer>', Writer='null', PollInterval='30', TableName='countersamples']
2015-11-05 15:57:20,867 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2015-11-05 15:57:20,867 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2015-11-05 15:57:20,867 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)

**Comment by Tabuser** [comment] 2015-11-05 22:06
sorry I am not able to attach the files as I dont have write permissions. Here is the tabmon config file

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="30"/>
  
  <Clusters>
    <Cluster name="Primary">
      <Host name="localhost"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
  </Database>
</TabMonConfig>

**Comment by Tabuser** [comment] 2015-11-05 22:12
Can I get the exact location for the temp directory where can I get the db creation log?

**Comment by danjrahm** [comment] 2015-11-06 00:09
The temp directory should be here: C:\Temp

It looks like github is messing up the XML, to workaround this you can email me the files at drahm@tableau.com.
If possible please email me all of the files I previously requested.

**Comment by Tabuser** [comment] 2015-11-07 18:18
Hi Dan,

I sent you the requested files through my company id. Please check it

**Comment by ddubrul** [comment] 2015-11-09 15:50
I am also receiving the error "error 5 access is denied" when attempting to start the tabmon service.

I checked the tabmon.log and it says:

2015-11-09 10:46:58,608 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2015-11-09 10:46:58,686 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2015-11-09 10:46:58,686 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2015-11-09 10:46:58,920 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"
2015-11-09 10:46:58,920 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'localhost' to 'AMTROWTABWRKD01'.
2015-11-09 10:46:58,935 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\AMTROWTABWRKD01', Writer='null', PollInterval='30', TableName='countersamples']
2015-11-09 10:46:58,935 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2015-11-09 10:46:58,935 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2015-11-09 10:46:58,935 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)  


I see where it says "password authentication failed for user tabmon".  I am using the default value for the tabmon password during the initial setup.  Should I be using something else?

**Comment by Tabuser** [comment] 2015-11-09 15:57
When I installed for the first time, I changed the password. As it was failing I uninstalled tabmon and the postgre and reinstalled with the default passoword as mentioned in the config file.
Also, forgot to tell, I am running my tableau server on windows 2012. Does it have anything to do with it?

**Comment by danjrahm** [comment] 2015-11-09 18:55
Did you by chance uninstall the TabMon-Postgres service?

**Comment by ddubrul** [comment] 2015-11-09 18:58
Hi Daniel –

Thanks for getting back to me.  I am going to try the uninstall/reinstall option with a different directory.

I did not uninstall tabmon-postgres service.  In the list of programs to uninstall I see postgresql 9.4 and psqlodbc but nothing specific to Tabmon postgres.



Thanks,

Doug
_________________________________________________________________________________________________________________________________________________________
Doug Dubrul | Systems Engineering & Management, Global Infrastructure |  Kelly Services, Inc. | +1 248.244.5532 (phone) | +1 248.821.3851 (cell) | doug.dubrul@kellyservices.com<mailto:Doug.Dubrul@kellyservices.com_>

**Comment by Tabuser** [comment] 2015-11-09 19:13
No I did not.

**Comment by danjrahm** [comment] 2015-11-09 20:13
That makes sense. So, the reason TabMon won't start is that the original database is up and running. The tabmon user on that database is still using the custom password that was used to install TabMon the first time.

There are 2 ways that I can think of that will resolve/workaround this.
1. Uninstall TabMon and TabMon-Postgres and reinstall the software.
2. Access the TabMon postgres installation using the tabmonsuperuser and delete/re-create the tabmon user.

If there are any questions about these options let me know.

**Comment by Tabuser** [comment] 2015-11-09 20:18
Uninstalling of the software will uninstall the services as well right? Hence I did not worry about it. Also, I made sure I deleted the folders as per the user guide.
Anyways, will try and update you.
Thank you

**Comment by danjrahm** [comment] 2015-11-09 22:26
So currently the uninstaller does not uninstall the postgres service. This is because we wanted to avoid accidental deletions of the data in postgres. We do however list the uninstall steps in our setup guide.

If there are any questions about uninstalling the service please let me know.

**Comment by danjrahm** [comment] 2015-11-11 17:52
I'm just checking in to see how the reinstall went. 

It also occurred to me that there may be another instance of Postgres running on the host. Can you get me a netstat? The command is below:

netstat -anb > C:\netstat.txt

**Comment by danjrahm** [comment] 2015-11-24 21:18
Hello, just checking in to see it this is resolved.

**Comment by rarandall** [comment] 2015-12-28 23:00
I was having this exact issue... Error 5: Access is Denied and the same log file output.
Turns out I already had PostgreSQL installed in a different directory. 

Uninstalling postgres and reinstalling Tabmon fixed the issues and everything is now working.

Hope this helps...
rr

**Comment by jmangue** [comment] 2016-01-09 21:43
Thanks for chiming in to help, rarandall!

Closing this issue out due to inactivity, please reopen it if you still need further assistance.

**Comment by Tabuser** [comment] 2016-01-09 21:47
Hey Justin,

Sorry, Was busy with some other stuff and holidays.
The issue is still open. I am not able to delete the tabmon postgre to
reinstall it. I do need some assistance on this.

Thanks

**Comment by jmangue** [comment] 2016-01-09 22:14
No problem, I know how it goes :)  Hope you had happy holidays.

There's some guidance on how to delete the TabMon Postgres instance on page 9 of the User Guide which I'll paste here:

Open up a console window as administrator and enter these commands:
sc stop TabMon-Postgres
sc delete TabMon-Postgres
... then delete the folder where you told TabMon to install Postgres (default is C:\Postgres)

At that point, you should be able to reinstall TabMon.  Sorry for the hassle on this; as Dan said, we leave Postgres in place during uninstall to prevent the customer from accidentally losing their data.

**Comment by Tabuser** [comment] 2016-01-09 23:34
Ok. Thanks. I will try and let you know.

**Comment by Tabuser** [comment] 2016-01-15 13:53
Hi,

It was installed successfully. Thank you. 
I have a question, Do we need to install the Windows Framework Manager 3.0 on Windows server 2012r2 as well. I'm able to see the articles which says 3.0 is compatible only till windowss 2008.
Is that true?

Thanks

**Comment by jmangue** [comment] 2016-01-17 22:18
Hi,

Glad to hear you got it installed successfully!

If you already have TabMon installed and working correctly, you don't need to worry about Windows Management Framework -- we only require that during installation, in order to run some database initialization commands in Powershell.  It looks like Windows 2012R2 actually includes Powershell, so you're all set.

Mind if I close this out?

**Comment by jmangue** [comment] 2016-01-21 05:55
Closing out, reopen if you need additional help on this issue.

**Closed by jmangue** 2016-01-21 05:55 UTC
Labels: help wanted

**Comment by Tabuser** [comment] 2016-01-21 12:39
OK. Thanks Justin.
You can close the issue.
Thanks for the amazing support you guys are giving.

**Comment by Shobananpa** [comment] 2016-06-14 18:28
Hi Team,
Could you please explain this step
2. Access the TabMon postgres installation using the tabmonsuperuser and delete/re-create the tabmon user.
Thanks,
Shoba
