### ISSUE TITLE
TabMon-Postgres Service unable to start

### ISSUE THREAD

**Issue by rishabh1991** [tableau/TabMon#93] opened 2016-09-12 09:36 UTC
I have installed new version of tabmon and I have installed it on D drive instead of C drive. Also currently I am using Tableau version 10.0 in HA environment.

When I am trying to run TabMon-Postgres service it throws below error:
![1](https://cloud.githubusercontent.com/assets/17762245/18431326/6f4e4560-78aa-11e6-980a-9c522470981f.png)

Upon checking I found still this service is taking default path for Postgress. How can I change it to D drive?
![2](https://cloud.githubusercontent.com/assets/17762245/18431445/dac24d14-78aa-11e6-8f15-2ae514718295.png)

**Comment by jmangue** [comment] 2016-09-12 21:00
Hi rishabh,

Interesting -- did you used to have TabMon installed on a different drive?  Typically the Postgres install path will be whatever you set it to in the Options menu of the installer.  I'm wondering if there is an unanticipated upgrade scenario which can cause this to break.

Anyways, in order to get up and running again...

Is your Postgres installed at D:\Postgres ?  If so, you can update the service properties to point to this location by opening an Administrator command prompt and issuing the following command:

> sc config TabMon-Postgres binPath= "\"D:\Postgres\bin\pg_ctl.exe\" runservice -N \"TabMon-Postgres\" -D \"D:\Postgres\data\""

Then refresh the Services window and try to start the TabMon-Postgres service.  Let me know how it goes.

**Comment by rishabh1991** [comment] 2016-09-13 09:52
Thanks, I tried the command, it fixes the Postgres service.

However, TabMon won't run, cause the DB isn't created properly.
After some investigation I found these results.

The TabMon installation fails at initialization of the DB because of [this](https://github.com/tableau/TabMon/blob/master/TabMonServiceInstallerDBInitializer/PGSetup.ps1#L4) hard coded value, it fails at [this](https://github.com/tableau/TabMon/blob/master/TabMonServiceInstallerDBInitializer/PGSetup.ps1#L22) step.

**Comment by jmangue** [comment] 2016-09-13 17:03
Glad to hear it's working right for you now.

That value you link is actually just a default value that is supposed to be overwritten/passed in at script execution time by the directory that the Postgres install folder that the user chooses from the installer (see powershell invocation [here])(https://github.com/tableau/TabMon/blob/master/TabMonServiceInstallerDBInitializer/Product.wxs#L63).. but clearly we have a bug somewhere (possibly in the upgrade scenario) since you hit this.  I'm labelling this as a bug for us to investigate, thanks for the report.

**Comment by msc0240** [comment] 2017-03-16 17:13
Hi,

Do we need to enable PostgreSQL option while installing Tab Mon ?

Tableau has its own PostgreSQL right, So in this case is it mandatory  to enable that option while installing Tab Mon?



![capture](https://cloud.githubusercontent.com/assets/20826839/24009080/0c0a413e-0a31-11e7-92ab-d8057ac3dcfb.PNG)

**Comment by danjrahm** [comment] 2017-03-16 17:38
While you don't need to install postgres with TabMon it is highly recommended that you have a separate postgres environment to store the data.

Please do not attempt to store TabMon data in Tableau Server's postgres. Doing so can cause performance issues and could potential corrupt postgres if something terrible happens.

If you would like to manually setup postgres I would start with this link:
https://www.postgresql.org/download/

**Comment by msc0240** [comment] 2017-03-16 18:00
Thanks for that Info.

We have our Tableau PostgreSQL installed. But  as a part of Performance Testing while installing Tab Mon, do we need to click on " Install and initialize Postgres for me"  option.

**Comment by danjrahm** [comment] 2017-03-16 19:11
I'm not sure what you mean by Tableau Postgresql. Do you mean the postgres server installed with Tableau Server?

**Comment by jmangue** [comment] 2017-06-26 17:25
@msc0240 If you still need help can you please open a new issue?

**Comment by danjrahm** [comment] 2017-09-12 21:47
I looked into this. 

I agree with Justin, I think the issue is that there was a previous install of TabMon-Postgres on the C drive. After uninstalling TabMon, it looks like the postgres directory was manually removed from the C drive. The failure happens because the service was never removed before installing TabMon and Postgres on the D drive, this means the existing service points at a non-existent postgres directory.

Using the manual uninstallation steps outlined on page 13 of the user guide will help avoid the issue.

I'm going to close this one out.

**Closed by danjrahm** 2017-09-12 21:47 UTC
Labels: bug
