### ISSUE TITLE
Tabmon service failing to start, "service terminated abnormally"

### ISSUE THREAD

**Issue by rishabh1991** [tableau/TabMon#130] opened 2017-09-08 06:31 UTC
Hi Team,

Tabmon services are abnormally getting terminated. This is happening very frequent.
Below is the log:

2017-07-16 18:03:30,971 [425] INFO TabMon.Sampler.CounterSampler - Finished polling 263 counters. [162 failures]
2017-07-16 18:03:31,003 [425] DEBUG TabMon.Sampler.CounterSamplerResultHelper - Compressed 101 rows into 52 unique rows..
2017-07-16 18:03:31,003 [425] DEBUG DataTableWriter.Writers.DataTableDbWriter - Writing 52 records to database..
2017-07-16 18:03:31,065 [425] DEBUG DataTableWriter.Writers.DataTableDbWriter - Finished writing 52 records!
2017-07-16 18:03:31,065 [425] DEBUG DataTableWriter.Adapters.DbAdapter - Dropping rows from table 'countersamples' older than 60 days..
2017-07-16 18:03:52,768 [137] INFO TabMon.Sampler.CounterSampler - Polling..
2017-07-16 18:03:52,768 [137] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading ephemeral performance counters from D:\Program Files (x86)\TabMon\Config\Counters.config..
2017-07-16 18:03:52,768 [137] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading Perfmon counters..
2017-07-16 18:04:52,678 [137] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service threw an unhandled exception
System.IO.IOException: The network path was not found.

   at Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view)
   at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName)
   at System.Diagnostics.PerformanceCounterLib.FindCustomCategory(String category, PerformanceCounterCategoryType& categoryType)
   at System.Diagnostics.PerformanceCounterLib.IsCustomCategory(String machine, String category)
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName)
   at TabMon.Counters.Perfmon.PerfmonCounterLoader.ExistsCategory(String categoryName, String machineName)
   at TabMon.Counters.Perfmon.PerfmonCounterLoader.LoadInstancesForCounter(Host host, CounterLifecycleType lifecycleType, String categoryName, String counterName, String unitOfMeasurement, ISet`1 instanceFilters)
   at TabMon.CounterConfig.PerfmonCounterConfigReader.LoadCounters(XmlNode root, Host host, CounterLifecycleType lifeCycleTypeToLoad)
   at TabMon.CounterConfig.CounterConfigLoader.Load(IEnumerable`1 hosts, CounterLifecycleType counterLifecycleType)
   at TabMon.Sampler.CounterSampler.SampleAll()
   at TabMon.TabMonAgent.Poll()
   at TabMon.TabMonAgent.OnTimer(Object stateInfo)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
2017-07-16 18:04:54,381 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-07-16 18:04:54,459 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-07-16 18:04:54,459 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-07-16 18:04:54,850 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas03.staplesams.com' to 'wtabpnas03'.
2017-07-16 18:04:54,850 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas01.staplesams.com' to 'wtabpnas01'.
2017-07-16 18:04:54,850 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas02.staplesams.com' to 'wtabpnas02'.
2017-07-16 18:04:54,865 [5] INFO TabMon.Config.TabMonConfigReader - Successfully loaded TabMon config options! [Hosts='wtabpnas03\wtabpnas03,wtabpnas03\wtabpnas01,wtabpnas03\wtabpnas02', Writer='Database Writer (Postgres Driver)', PollInterval='30', TableName='countersamples']
2017-07-16 18:04:54,865 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-07-16 18:04:54,881 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading persistent performance counters from D:\Program Files (x86)\TabMon\Config\Counters.config..
2017-07-16 18:04:54,881 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading performance counters from D:\Program Files (x86)\TabMon\Config\Counters.config..
2017-07-16 18:04:54,897 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Successfully validated 'Config\Counters.config' against 'Resources\CountersConfig.xsd'.
2017-07-16 18:04:54,897 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading Perfmon counters..
2017-07-16 18:05:15,941 [5] ERROR TabMon.TabMonAgent - Failed to initialize counter sampler using counters from configuration file: The network path was not found.

Aborting..
2017-07-16 18:05:15,941 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-07-16 18:05:15,957 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)
2017-08-12 14:45:57,001 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-08-12 14:45:57,079 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-08-12 14:45:57,079 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-08-12 14:45:58,298 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 57P03: the database system is starting up
2017-08-12 14:45:58,298 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas03.staplesams.com' to 'wtabpnas03'.
2017-08-12 14:45:58,298 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas01.staplesams.com' to 'wtabpnas01'.
2017-08-12 14:45:58,298 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas02.staplesams.com' to 'wtabpnas02'.
2017-08-12 14:45:58,548 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Hosts='wtabpnas03\wtabpnas03,wtabpnas03\wtabpnas01,wtabpnas03\wtabpnas02', Writer='null', PollInterval='30', TableName='countersamples']
2017-08-12 14:45:58,548 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-08-12 14:45:58,548 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2017-08-12 14:45:58,564 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-08-12 14:46:13,498 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)
2017-08-24 08:44:35,670 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-08-24 08:44:35,780 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-08-24 08:44:35,780 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-08-24 08:44:37,061 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
2017-08-24 08:44:37,077 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas03.staplesams.com' to 'wtabpnas03'.
2017-08-24 08:44:37,077 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas01.staplesams.com' to 'wtabpnas01'.
2017-08-24 08:44:37,077 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wtabpnas02.staplesams.com' to 'wtabpnas02'.
2017-08-24 08:44:37,280 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Hosts='wtabpnas03\wtabpnas03,wtabpnas03\wtabpnas01,wtabpnas03\wtabpnas02', Writer='null', PollInterval='30', TableName='countersamples']
2017-08-24 08:44:37,280 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-08-24 08:44:37,280 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2017-08-24 08:44:37,295 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-08-24 08:44:51,546 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

Can you please let me know, what issue is happeneing over here.

Thanks 
Rishabh Tripathi

**Comment by danjrahm** [comment] 2017-09-12 23:08
Hey Rishabh,

It looks like the issue is that TabMon cannot resolve the computer name used to query the windows performance counters. 

For the next steps, can you try specifying the windows computer names for all of the servers in the tabmon config as opposed to the FQDN? 

For example, 'wtabpnas02.staplesams.com' would become the actual windows computer name in the config. This should be the System Name in System Info

Overall, I think you may be running into issue #99. I am currently looking into fixes for that.

Thanks,
Dan

**Comment by rishabh1991** [comment] 2017-09-13 06:45
Hi Dan,

I am using below config file. Please let me know what needs to be changed.

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="30"/>
  
  <Clusters>
    <Cluster name="wtabpnas03">
      <Host name="wtabpnas03.staplesams.com"/>
      <Host name="wtabpnas01.staplesams.com"/>
       <Host name="wtabpnas02.staplesams.com"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="wtabpnas02" port="5432"/>
    <User login="tabmon" password="**********"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="true" thresholdDays="60"/>
  </Database>
</TabMonConfig>

**Comment by rishabh1991** [comment] 2017-09-13 06:46
<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="30"/>
  
  <Clusters>
    <Cluster name="wtabpnas03">
      <Host name="wtabpnas03.staplesams.com"/>
      <Host name="wtabpnas01.staplesams.com"/>
       <Host name="wtabpnas02.staplesams.com"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="wtabpnas02" port="5432"/>
    <User login="tabmon" password="*******"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="true" thresholdDays="60"/>
  </Database>
</TabMonConfig>

**Comment by danjrahm** [comment] 2017-09-13 20:51
Hi Rishabh,

I can't see the config. Can you please try sending it again?

-Dan

**Comment by rishabh1991** [comment] 2017-09-14 07:18
Hi Dan,

Please find attachment.

RIshabh
[config.docx](https://github.com/tableau/TabMon/files/1302036/config.docx)

**Comment by danjrahm** [comment] 2017-09-14 22:17
Hey Rishab,

You'll need to change these three settings to the computer names.
<Host name="wtabpnas03.staplesams.com"/>
<Host name="wtabpnas01.staplesams.com"/>
<Host name="wtabpnas02.staplesams.com"/>

To figure out the computer name, open a Command Prompt window on each computer and run 'hostname'. Please use those names in the config options above.

-Dan

**Comment by rishabh1991** [comment] 2017-09-15 06:06
Hi Dan,

I am unable to see your whole message.
Can you please send it again?

Thanks 
Rishabh

**Comment by danjrahm** [comment] 2017-09-15 22:26
Sorry about that. A text file with the lines is attached.
[ChangeTheseLines.txt](https://github.com/tableau/TabMon/files/1307847/ChangeTheseLines.txt)

As I mentioned above. You'll need to change these three settings to the computer names.

To figure out the computer name, open a Command Prompt window on each computer and run 'hostname'. Please use those names in the config options above.

-Dan

**Comment by danjrahm** [comment] 2017-09-21 22:56
Hi Rishabh,

Did these changes work for you?

Thanks,
Dan

**Comment by rishabh1991** [comment] 2017-09-25 08:34
Hi Dan,

Sorry for late reply.
I was monitoring the service was whole week and the service didn't went down.
Thanks for your help !

Thanks 
Rishabh Tripathi

**Comment by danjrahm** [comment] 2017-09-25 18:13
Hi Rishabh,

I'm happy to hear that everything is working now. 

Just as a heads up, or next release will address this exact issue. We address this by making users specify a computer name and address for every host within a cluster. This is all noted here: https://tableau.github.io/TabMon/docs/tabmon_configure#tabmonconfig

Let me know if you have any other questions. I'm closing this out now.

Thanks,
Dan

**Closed by danjrahm** 2017-09-25 18:13 UTC
